Implement user symbol translation for BPFd
joelagnel/bpfd pull request #26
Opened 2018-03-09 00:42 UTC by jcanseco

2018-03-09 00:42 UTC, jcanseco commented
This depends on PR #25.

2018-03-09 07:20 UTC, joelagnel commented
I don't see the point of the extra `SymbolResolver` class really. The centralization argument is too weak to warrant create a new C++ source file and the cache creation can be done only once per-pid from bpfd.c itself, instead of creating it every time on every lookup command.

2018-03-09 07:23 UTC, joelagnel requested changes

2018-03-09 07:23 UTC, joelagnel commented on src/bpfd.c
> +			usym_cache = bcc_symcache_new(pid, NULL);
Instead of introducing an issue (creation of cache every time), and fixing it in a later commit, you should design it correctly to begin with.

2018-03-09 19:35 UTC, jcanseco commented
Hey, so I wasn't 100% sure if the SymbolResolver class was the way to go, which is why I added it as a separate commit for now, so that I can easily reverse it if you did not think it was a good idea.

The issue of having an extra commit aside though, how can we do the caching of the ProcSyms instances just from bpfd.c? I basically introduced SymbolResolver so we can take advantage of the C++'s std::unordered_map as a nice way to cache ProcSyms for each pid (so that we don't recreate it for every sym lookup for each pid), but I'm kind of confused how we can efficiently replicate this functionality from just C in bpfd.c alone. Am I just missing something here?

2018-03-09 19:55 UTC, joelagnel commented
Just create an array of PID->pointers

2018-03-09 20:16 UTC, jcanseco commented
Okay, so what kind of implementation are looking at here?

I'm assuming we're thinking of something like this:

We're gonna use an array as our main data structure for holding references to the ProcSyms instances.

The array itself can be an array of usym structs, where a usym struct can be defined as:

```
struct  usym {
    int pid;
    void *usym_cache;
}
```
This way we can retrieve the ProcSyms instance that belongs to a given PID. We can also find out for which PIDs we've previously created a ProcSyms instance for.

The problem I see with this though is how do we handle the case where the array becomes filled to capacity, and we have to create another ProcSyms instance? I understand we can just create a new array and copy all the elements over, but this'll be just somewhat of a re-implementation of std::vector.

Also, PID lookup in this case would be O(n) since we would have to traverse the whole array in the worst-case scenario to find the particular PID we're looking for, as opposed to std::unordered_map's O(1) lookup. Wouldn't this hamper performance since some BCC tools perform _a lot_ of symbol lookups?

I'm still somewhat of a beginner at C and my background is mostly OOP, so please forgive me if this is actually just an obvious problem.

2018-03-09 20:22 UTC, joelagnel commented
You can index the array with the PID which makes look up O(1). 32768 is typically maximum pids in Linux, but if a rare collision occurs (say max pids run out or a pid is reused), then a collision can be detected easily by storing the full name of the exe along with the PID in the array. To handle the case of number of PIDS > 32k, which isn't the default - you can easily just store the full PID and the full EXE name and detect collisions. Incase of collisions, just return "unknown". I'd say worry about these cases later though and for now just do a plain PID->ProcSyms(or whatever ptr) array mapping.

2018-03-09 20:24 UTC, joelagnel commented
You're not handling collisions or the special cases in your earlier PR
anyway by the way...

On Fri, Mar 9, 2018 at 11:35 AM, Jazel Canseco <notifications@github.com>
wrote:

> Hey, so I wasn't 100% sure if the SymbolResolver class was the way to go,
> which is why I added it as a separate commit for now, so that I can easily
> reverse it if you did not think it was a good idea.
>
> The issue of having an extra commit aside though, how can we do the
> caching of the ProcSyms instances just from bpfd.c? I basically introduced
> SymbolResolver so we can take advantage of the C++'s std::unordered_map as
> a nice way to cache ProcSyms for each pid (so that we don't recreate it for
> every sym lookup for each pid), but I'm kind of confused how we can
> efficiently replicate this functionality from just C in bpfd.c alone. Am I
> just missing something here?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/joelagnel/bpfd/pull/26#issuecomment-371922806>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AACSVA7dlGkKEm5UjXX__-tbDdxNpIA1ks5tctmFgaJpZM4Sjk5u>
> .
>

2018-03-09 20:30 UTC, jcanseco commented
Ah okay that explains it then. I didn't know there was a max cap for PIDs in Linux. I'll deal with this problem in a bit then.

2018-03-09 20:35 UTC, joelagnel commented
Default is 32k, so that's why I mentioned to handle collisions. If a collision occurs, its just fair to make the request fail for now.

2018-03-09 22:06 UTC, jcanseco commented
For the collisions scenario, isn't it enough to just return a failure if the given PID goes over the 32k default cap? (i.e. no need to check if a ProcSyms already exists at the index PID % 32k)

For the other type of collision (where the PID is reused for a different process), wouldn't it be better to just overwrite the existing ProcSyms we cached before for that PID? After all, the PID->ProcSyms mapping held at that index is now outdated. Also, this seems better to me since then we can still return a successful lookup instead of just outright failing the request.

2018-03-09 22:08 UTC, jcanseco commented
Also please see the most recent change I made. I'll squash it later into the first commit; I just want to bring your attention to the changes I made related to caching ProcSyms to see if it's suitable.

2018-03-09 22:20 UTC, jcanseco commented
Added another commit that checks for the PID going over the default max of 32k. I also plan to squash this with the first commit ("Implement user symbol translation for BPFd")

2018-03-10 09:16 UTC, joelagnel commented
No. If PIDs are > 32k and nothing less than 32k was cached, then it should be cached since there's nothing to collide with. In other words its normal and not an error.

2018-03-12 22:50 UTC, jcanseco commented
Okay, how about this one (see most recent commit).

It caches the ProcSyms instance, and handles both collision cases (pid reuse and pid wrap-around due to 32k cap).

Let me know what you think.

2018-03-13 00:38 UTC, joelagnel requested changes

2018-03-13 00:38 UTC, joelagnel commented on src/bpfd.c
> +	struct usym_cache *usym_caches[DEFAULT_MAX_PID] = { NULL };
Dynamically allocate and free it. Don't use the stack for large structs.

2018-03-13 00:38 UTC, joelagnel commented on src/bpfd.c
> +			usym_cache_ = (struct usym_cache *)malloc(sizeof(struct usym_cache));
why aren't you free it at the end of the program?

2018-03-13 00:38 UTC, joelagnel commented on src/bpfd.c
> +	char *exe_path = (char *)malloc(PATHBUF_SIZE);
Where are you freeing all the exe_path at the end of the program?

2018-03-13 18:08 UTC, jcanseco commented on src/bpfd.c
> +	struct usym_cache *usym_caches[DEFAULT_MAX_PID] = { NULL };
Done.

2018-03-13 18:08 UTC, jcanseco commented on src/bpfd.c
> +	char *exe_path = (char *)malloc(PATHBUF_SIZE);
Done.

2018-03-13 18:08 UTC, jcanseco commented on src/bpfd.c
> +			usym_cache_ = (struct usym_cache *)malloc(sizeof(struct usym_cache));
Done.

2018-03-13 18:08 UTC, jcanseco commented
Made the requested changes. PTAL.

2018-03-16 12:34 UTC, joelagnel approved these changes

2018-03-16 12:34 UTC, merged