Proposed solution to Issue #1
joelagnel/bpfd pull request #9
Opened 2018-01-11 18:27 UTC by ammon0

2018-01-11 18:51 UTC, joelagnel requested changes

2018-01-11 18:51 UTC, joelagnel commented on src/utils.c
> +/*	tracef[0] = 0;*/
why are the comments still here?

2018-01-11 18:51 UTC, joelagnel commented on src/utils.c
> +	memcpy(tracef, tracefs, len_tfs);
strcat

2018-01-11 18:51 UTC, joelagnel commented on src/utils.c
> +	return_val = cat_file(tracef);
thanks for the effort, could you follow the style guidelines before posting:
https://www.kernel.org/doc/html/v4.10/process/coding-style.html

2018-01-11 18:51 UTC, joelagnel commented on src/utils.c
> +	memcpy(tracef, tracefs, len_tfs);
The other way might be, just use strncat and then we don't need to malloc at all.

2018-01-11 18:51 UTC, joelagnel commented on src/bpfd.c
> +	char * tracef;
char *tracef;

2018-01-11 20:49 UTC, ammon0 commented
I don't understand how strncat could be a solution,
- the size parameter only applies to the source string
- I would still have to use strlen to keep a running tally of space remaining in the destination buffer
- on failure strncat would silently truncate

If we're committed to the fixed length buffers I could also just check total length first and fail before calling strcat.

I can push another commit when I get clarification. I'll also clean up the formatting as per your request.

2018-01-11 20:58 UTC, joelagnel commented
Why?
`strncat` prevents overflow on the destination, by ensuring we don't cross its boundaries.
See: [https://linux.die.net/man/3/strncat](https://linux.die.net/man/3/strncat)
```
char tracef[256];
strncat(tracef, tracefs, 256)
strncat(tracef, '/', 256)
strncat(tracef, category, 256)
```
The only drawback is we'rd hardcoding the length, but atleast that's better than dynamic memory allocation failure for any reason IMO.

2018-01-16 00:36 UTC, ammon0 commented
In principle I agree with you that strncat would be most useful if it protected the destination buffer from overflow. However, as I said previously, that is not how strncat works. Quoting from the [link](https://linux.die.net/man/3/strncat) you sent me:

"...the dest string must have enough space for the result. If dest is not large enough, program behavior is unpredictable; buffer overruns are a favorite avenue for attacking secure programs. "

strncat's size parameter limits the number of characters read from the **source** string, not the total number of characters written to the destination string. For example, the following code crashes because of stack smashing. Each string individually is shorter than the limit, but together they overflow the destination buffer.

#include <string.h>
#include <stdio.h>
#define BUF 20

int main(){
	char tracef[BUF];
	
	strncat(tracef, "FIRST STRING. ", BUF);
	strncat(tracef, "SECOND STRING.", BUF);
	puts(tracef);
	return 0;
}

I have reverted my two previous commits since they were unsatisfactory and I thought it better to start fresh--they weren't that great anyway. I then made a single commit that should correct issue #1 without using dynamic allocation by checking the total length before actually writing to the buffer.

Please let me know if I screwed anything else up.

2018-01-16 02:22 UTC, joelagnel commented
Yes you screwed up, and you are reading the wrong documentation and wasting my time.
The documentation you quoted is for `strcat`. `strncat` on the other hand makes sure not to overflow the destination. The link I sent you is documentation for both `strcat` and `strncat`.
Also no need to revert commits that were never merged. You can just rebase your local branch and remove the commits you don't want. I am not going to merge your revert commits from your PR :)

2018-01-16 20:45 UTC, blaine-dodson commented
Sorry. I'm done.

2018-01-16 20:45 UTC, closed without merging